### PR TITLE
Fix build failure against PySide >= 6.8

### LINKED ISSUE #3384: Build failure against PySide >= 6.8
**Environment information**
* Operating System: NixOS
* Cutter version: 
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

`PySide::SignalManager::instance()` was removed [here](https://code.qt.io/cgit/pyside/pyside-setup.git/diff/sources/pyside6/libpyside/signalmanager.h?id=33bd61d13d8d9e3794b6049891be62f3351313d9) in [this commit](https://code.qt.io/cgit/pyside/pyside-setup.git/commit/sources/pyside6?id=33bd61d13d8d9e3794b6049891be62f3351313d9), before the release of 6.8.0.

This change in pyside caused a compilation error on `cutter/src/common/PythonManager.cpp:136:28` which called `PySide::SignalManager::instance().clear();`:

```
/build/source/src/common/PythonManager.cpp:136:28: error: 'instance' is not a member of 'PySide::SignalManager'
  136 |     PySide::SignalManager::instance().clear();
```

Inferring from code in that same commit, it seems that this line is no longer needed.
But I'm not sure as I'm not familiar with Qt.

**To Reproduce**

Build cutter against Qt & PySide >= 6.8

**Expected behavior**

No build failure.

**Additional context**

The full compilation log can be viewed on the build server of NixOS. [link](https://hydra.nixos.org/build/274852839/nixlog/1)

### PR DESCRIPTION
**Pull request by karliss**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Seems like some of the implementation details changed, removing the need for manual cleanup thus the function doesn't exist anymore. https://github.com/pyside/pyside-setup/commit/33bd61d13d8d9e3794b6049891be62f3351313d9

**Test plan (required)**

* Still compiles  against Pyside < 6.8 - should be covered by CI tests, and the effective code should be identical to before
* Compiles with Pyside 6.8 (need to use CUTTER_ENABLE_PYHON and CUTTER_ENABLE_PYTHON_BINDINGS)  - tested on ArchLinux  :heavy_check_mark: 
* With Pyside 6.8 Cutter exits cleanly without any crashes or new warning messages :heavy_check_mark: 

**Closing issues**

closes #3384

### CODE REVIEW

**Review by wargio — APPROVED** [review]

File: src/common/PythonManager.cpp [hunk 1]
```diff
@@ -133,7 +133,9 @@ void PythonManager::shutdown()
     Core()->setProperty("_PySideInvalidatePtr", QVariant());
 
     // see PySide::destroyQCoreApplication()
+#    if QT_VERSION < QT_VERSION_CHECK(6, 8, 0)
     PySide::SignalManager::instance().clear();
+#    endif
```
Comment (wargio) [inline src/common/PythonManager.cpp:138]: is this clang-formatted ?

Comment (karliss) [reply src/common/PythonManager.cpp:138]: Yes, that's why the force push from 441a520 to 198541c.  Initially had it without indentation, but Clang formatter in CI complained.

**Review by XVilka — APPROVED** [review]

File: src/common/PythonManager.cpp (hunk 1 above)
Comment (karliss) [reply src/common/PythonManager.cpp:138]: I have to say looks a bit weird especially without additional context.

Seems like in current config clang-format does 4 space indentation (in addition to `#`) for nested `#if ` blocks.  Not a problem for code that contains only preprocessor statements, not a problem if there is single level of `#if` combined with regular code. But second level of `#if` mixed with regular code results in the weird off by one indentation you see above.
